// English reference texts for the application
// These are used when language is set to 'en'
// The key structure matches the Arabic translations in translations.js

export const englishTexts = {
  'app.dashboard': 'Dashboard',
  'app.home': 'Home',
  'app.settings': 'Settings',
  'app.reports': 'Reports',
  'app.notifications': 'Notifications',
  'app.profile': 'Profile',
  'app.logout': 'Logout',
  'app.admin': 'Admin',
  'app.user': 'User',
  'app.users': 'Users',
  'app.roles_permissions': 'Roles & Permissions',
  
  'buttons.add_new': 'Add New',
  'buttons.edit': 'Edit',
  'buttons.save': 'Save',
  'buttons.cancel': 'Cancel',
  'buttons.delete': 'Delete',
  'buttons.view': 'View',
  'buttons.details': 'Details',
  'buttons.search': 'Search',
  'buttons.filter': 'Filter',
  'buttons.export': 'Export',
  'buttons.print': 'Print',
  'buttons.refresh': 'Refresh',
  'buttons.back': 'Back',
  'buttons.confirm': 'Confirm',
  'buttons.close': 'Close',
  
  'customers.customers': 'Customers',
  'customers.add_customer': 'Add Customer',
  'customers.edit_customer': 'Edit Customer',
  'customers.delete_customer': 'Delete Customer',
  'customers.customer_profile': 'Customer Profile',
  'customers.view_vehicles': 'View Vehicles',
  'customers.customer_balance': 'Customer Balance',
  'customers.customer_history': 'Customer History',
  
  'vehicles.vehicles': 'Vehicles',
  'vehicles.add_vehicle': 'Add Vehicle',
  'vehicles.edit_vehicle': 'Edit Vehicle',
  'vehicles.delete_vehicle': 'Delete Vehicle',
  'vehicles.vehicle_details': 'Vehicle Details',
  'vehicles.update_mileage': 'Update Mileage',
  'vehicles.service_history': 'Service History',
  'vehicles.plate_number': 'Plate Number',
  'vehicles.vin': 'VIN',
  'vehicles.model': 'Model',
  'vehicles.year': 'Year',
  'vehicles.mileage': 'Mileage',
  
  'status.status': 'Status',
  'status.open': 'Open',
  'status.in_progress': 'In Progress',
  'status.waiting_for_parts': 'Waiting for Parts',
  'status.completed': 'Completed',
  'status.delivered': 'Delivered',
  'status.cancelled': 'Cancelled',
  'status.diagnosis': 'Diagnosis',
  'status.waiting_approval': 'Waiting Approval',
  'status.quality_check': 'Quality Check',
  'status.ready': 'Ready for Delivery',
  
  'nav.dashboard': 'Dashboard',
  'nav.operations': 'Operations',
  'nav.customers': 'Customers',
  'nav.technicians': 'Technicians',
  'nav.suppliers': 'Suppliers',
  'nav.inventory': 'Inventory',
  'nav.services': 'Services',
  'nav.documents': 'Documents',
  'nav.finance': 'Finance',
  'nav.archive': 'Archive',
  'nav.import': 'Import Data',
  'nav.users': 'Users',
  'nav.profile': 'Profile',
  'nav.settings': 'Settings',
  
  'dashboard.title': 'Dashboard',
  'dashboard.overview': 'Workshop Overview',
  'dashboard.total_vehicles': 'Total Vehicles',
  'dashboard.in_progress': 'In Progress',
  'dashboard.ready': 'Ready for Delivery',
  'dashboard.technicians': 'Available Technicians',
  'dashboard.new_vehicle': 'New Vehicle',
  'dashboard.search': 'Search by customer name or plate number...',
  
  'common.all': 'All',
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.add': 'Add',
  'common.search': 'Search',
  'common.loading': 'Loading...',
  'common.no_data': 'No Data',
  'common.success': 'Success',
  'common.error': 'Error',
  'common.confirm_delete': 'Are you sure you want to delete?',
  'common.print': 'Print',
  'common.total': 'Total',
  'common.currency': 'SAR',
  
  'inventory.spare_parts': 'Spare Parts',
  'inventory.inventory': 'Inventory',
  'inventory.suppliers': 'Suppliers',
  'inventory.add_item': 'Add Item',
  'inventory.edit_item': 'Edit Item',
  'inventory.delete_item': 'Delete Item',
  'inventory.stock_in': 'Stock In',
  'inventory.stock_out': 'Stock Out',
  'inventory.low_stock_alert': 'Low Stock Alert',
  'inventory.item_code': 'Item Code',
  'inventory.quantity': 'Quantity',
  'inventory.unit_price': 'Unit Price',
  
  'reports_module.analytics': 'Analytics',
  'reports_module.daily_report': 'Daily Report',
  'reports_module.monthly_report': 'Monthly Report',
  'reports_module.financial_report': 'Financial Report',
  'reports_module.profit_loss': 'Profit & Loss',
  'reports_module.cash_flow': 'Cash Flow',
  'reports_module.export_pdf': 'Export PDF',
  'reports_module.export_excel': 'Export Excel',
  'reports_module.summary': 'Summary',
  'reports_module.kpi': 'KPIs',
  
  'work_orders.work_orders': 'Work Orders',
  'work_orders.create_work_order': 'Create Work Order',
  'work_orders.edit_work_order': 'Edit Work Order',
  'work_orders.assign_technician': 'Assign Technician',
  'work_orders.change_status': 'Change Status',
  'work_orders.start_work': 'Start Work',
  'work_orders.complete_work': 'Complete Work',
  'work_orders.deliver_vehicle': 'Deliver Vehicle',
  'work_orders.cancel_order': 'Cancel Order',
  'work_orders.job_description': 'Job Description',
  'work_orders.estimated_time': 'Estimated Time',
  'work_orders.completion_date': 'Completion Date',
  'work_orders.assigned_technician': 'Assigned Technician',
  
  'staff.technicians': 'Technicians',
  'staff.mechanic': 'Mechanic',
  'staff.supervisor': 'Supervisor',
  'staff.add_technician': 'Add Technician',
  'staff.edit_technician': 'Edit Technician',
  'staff.assign_job': 'Assign Job',
  'staff.attendance': 'Attendance',
  'staff.working_hours': 'Working Hours',
  'staff.performance_report': 'Performance Report',
  
  'invoices.invoices': 'Invoices',
  'invoices.create_invoice': 'Create Invoice',
  'invoices.edit_invoice': 'Edit Invoice',
  'invoices.delete_invoice': 'Delete Invoice',
  'invoices.view_invoice': 'View Invoice',
  'invoices.print_invoice': 'Print Invoice',
  'invoices.apply_discount': 'Apply Discount',
  'invoices.add_tax': 'Add Tax',
  'invoices.invoice_number': 'Invoice Number',
  'invoices.invoice_date': 'Invoice Date',
  'invoices.total_amount': 'Total Amount',
  'invoices.discount': 'Discount',
  'invoices.vat': 'VAT',
  'invoices.net_amount': 'Net Amount',
  
  'payments.payments': 'Payments',
  'payments.add_payment': 'Add Payment',
  'payments.payment_method': 'Payment Method',
  'payments.cash': 'Cash',
  'payments.credit_card': 'Credit Card',
  'payments.bank_transfer': 'Bank Transfer',
  'payments.mark_as_paid': 'Mark as Paid',
  'payments.partial_payment': 'Partial Payment',
  'payments.paid': 'Paid',
  'payments.unpaid': 'Unpaid',
  'payments.partially_paid': 'Partially Paid',
  
  'auth.login': 'Login',
  'auth.username': 'Username',
  'auth.password': 'Password',
  'auth.remember_me': 'Remember Me',
  'auth.forgot_password': 'Forgot Password?',
  'auth.change_password': 'Change Password',
  
  'system.backup': 'Backup',
  'system.restore': 'Restore',
  'system.system_settings': 'System Settings',
  
  // Messages
  'messages.success_saved': 'Saved Successfully',
  'messages.success_updated': 'Updated Successfully',
  'messages.success_deleted': 'Deleted Successfully',
  'messages.error_occurred': 'An Error Occurred',
  'messages.loading_data': 'Loading Data...',
  'messages.no_results': 'No Results Found',
  'messages.confirm_action': 'Are you sure?',
  'messages.action_cancelled': 'Action Cancelled',
  'messages.processing': 'Processing...',
  
  // Forms
  'forms.required_field': 'This field is required',
  'forms.invalid_email': 'Invalid email address',
  'forms.invalid_phone': 'Invalid phone number',
  'forms.name': 'Name',
  'forms.phone': 'Phone',
  'forms.email': 'Email',
  'forms.address': 'Address',
  'forms.notes': 'Notes',
  'forms.select': 'Select',
  'forms.select_option': 'Select an option'
};
