export const LIQUID_BUILDER_PAGES = [
  { path: '/', label: 'لوحة التحكم' },
  { path: '/operations', label: 'العمليات' },
  { path: '/debts-followup', label: 'متابعة الذمم' },
  { path: '/archive', label: 'الأرشيف' },
  { path: '/customers', label: 'العملاء' },
  { path: '/technicians', label: 'الفنيون' },
  { path: '/parts-dashboard', label: 'لوحة القطع' },
  { path: '/parts', label: 'المخزون' },
  { path: '/suppliers', label: 'الموردون' },
  { path: '/services', label: 'الخدمات' },
  { path: '/accounting/chart-of-accounts', label: 'دليل الحسابات' },
  { path: '/accounting/comprehensive', label: 'القوائم المالية' },
  { path: '/accounting/journal-entries', label: 'القيود اليومية' },
  { path: '/finance/taxes', label: 'الضرائب' },
  { path: '/ai-financial', label: 'المساعد الذكي الموحد' },
  { path: '/print', label: 'الطباعة' },
  { path: '/templates', label: 'القوالب' },
  { path: '/import', label: 'الاستيراد' },
  { path: '/users', label: 'المستخدمون' },
  { path: '/profile', label: 'ملف الورشة' },
  { path: '/settings', label: 'الإعدادات' },
  { path: '/moltbot', label: 'MoltBot' },
];